include(":configs")
include(":test-common")
include(":mvvm-common")
include(":app")
include(":localization")
include(":translation-processor")
include(":mvvm-common")
include(":restaurant-provider")
include(":test-common")
rootProject.name = "DroidCon 2020 Modularization Workshop"
